name: Build and Push Docker Image

on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: registry.24simplegeek.ru:5000
                  username: ${{ secrets.DEV_REGISTRY_USERNAME }}
                  password: ${{ secrets.DEV_REGISTRY_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build \
                    --build-arg SHOP_API_URL=${{ secrets.DEV_SHOP_API_URL }} \
                    --build-arg AUTH_API_URL=${{ secrets.DEV_AUTH_API_URL }} \
                    -t registry.24simplegeek.ru:5000/market-react-app-server:dev .

            - name: Push Docker image
              run: |
                  docker push registry.24simplegeek.ru:5000/market-react-app-server:dev
