name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to Docker Registry
              uses: docker/login-action@v1
              with:
                  registry: ${{ secrets.PROD_REGISTRY_URL }}
                  username: ${{ secrets.PROD_REGISTRY_USERNAME }}
                  password: ${{ secrets.PROD_REGISTRY_PASSWORD }}

            - name: Build Docker image
              run: |
                  docker build \
                    --build-arg SHOP_API_URL=${{ secrets.PROD_SHOP_API_URL }} \
                    --build-arg AUTH_API_URL=${{ secrets.PROD_AUTH_API_URL }} \
                    -t ${{ secrets.PROD_REGISTRY_URL }}/market-react-app-server:latest .

            - name: Push Docker image
              run: |
                  docker push ${{ secrets.PROD_REGISTRY_URL }}/market-react-app-server:latest
